services:
  roadrunner:
    build:
      dockerfile: .docker/roadrunner/Dockerfile
    container_name: roadrunner
#    image:
    ports:
      - "8080:8080"
    working_dir: "/srv"
    networks:
      - anxiety
    volumes:
      - ./:/srv
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      APP_ENV: dev
#    command: sh -c "composer install && bin/console c:c && rr serve"
#    command: sh -c "composer self-update --update-keys && composer diagnose && composer install && rr serve"
#    command: sh -c "composer install && rr --help"
#    command: sh -c "rr get-binary -f \"2024.1\""
#    command: sh -c "composer install && rr serve"
#    command: sh -c "composer create-project symfony/skeleton:"7.0.*" app"
#    command: sh -c "composer req --no-interaction baldinof/roadrunner-bundle"
    command: sh -c "rr serve -c .rr.dev.yaml --debug"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: postgres
    ports:
        - "5444:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-VeryCoolPassword}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - anxiety
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  anxiety:
    name: anxiety
    driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
